image: alpine:latest

variables:
  RUBYCORE_VERSION: 0.0.5

stages:
  - build
  - test
  - curseforge

build:
  stage: build
  image: gradle:6.8.1-jdk15
  script:
    - echo "Building $RUBYCORE_VERSION"
    - gradle build -Pversion=$RUBYCORE_VERSION
  artifacts:
    paths:
      - build/libs/rubycore-$RUBYCORE_VERSION.jar

lint-ruby:
  stage: test
  image: ruby:2.7.3

  script:
    - cd src/main/resources
    - bundle install
    - rubocop

test-ruby:
  stage: test
  image: ruby:2.7.3
  script:
    - cd src/main/resources
    - bundle install
    - rspec --pattern spec/**/*_spec.rb

include:
  - template: Jobs/Test.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/Test.gitlab-ci.yml
  - template: Jobs/Code-Quality.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/Code-Quality.gitlab-ci.yml
  - template: Jobs/Code-Intelligence.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/Code-Intelligence.gitlab-ci.yml
